name: Test

on:
    pull_request:
        branches: [ master ]


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Checkout submodules
              uses: textbook/git-checkout-submodule-action@master
            - name: Download Zola
              run: |
                curl https://api.github.com/repos/getzola/zola/releases/latest |
                    grep -o '"browser_download_url.*linux.*tar.gz"' |
                    cut -d : -f 2,3 |
                    tr -d \" |
                    wget -qi -
                gunzip zola*gz
                tar xf zola*tar
            - name: Build
              run: ./zola build
